### ISSUE TITLE
Skip gettext steps when disabled

### ISSUE THREAD

**Issue by dankohn** [aurels/translation-gem#18]
In our repo, we have [disabled](https://github.com/coreinfrastructure/best-practices-badge/blob/master/config/initializers/translation.rb#L17) gettext support. However, running the sync produces:
```sh
$ rake translation:sync
* Downloading YAML source editions.
* Applying YAML source editions.
* Updating POT file.
* Generating POT file from YAML files.
* Saving new PO files.
* Creating new MO files.
* Saving new translation YAML files.
* Saving new localization YAML files (with non-string values).
* Collecting YAML localization entries

----------
Use this URL to translate: http://translation.io/david-a-wheeler/cii-best-practices-badge
----------
```
Shouldn't the middle 4 steps involving POT, PO and MO files be skipped?

**Comment by MichaelHoste** [comment]
They are somewhat skipped using an empty list of files to parse : https://github.com/aurels/translation-gem/blob/master/lib/translation_io/client/base_operation/update_pot_file_step.rb#L9

We can't unfortunately totally ignore Gettext since we use its internal format to sync with the backend either with YAML or Gettext.
