### ISSUE TITLE
Errantly finding translation keys in markdown

### ISSUE THREAD

**Issue by woahdae** [aurels/translation-gem#3]
I have markdown in a haml file similar to the following (via my site's Terms of Service):

    :markdown
        These Terms of Service (**_“Terms”_**) govern your access to this website [...]

Here, it's finding `Terms` to be a translation key. A workaround could be to switch the operators: `__*"Terms"*__`, but I thought I'd bring up the issue so you're aware of it.

Note, we noticed because we translated our TOS into Spanish via `terms_of_service.es.html.haml`, and it saw `Términos` from `**_"Términos"_**`. So, a separate issue might be that the gem should recognize `es.html` as not being a source for english translation keys. In our case, though, fixing the main issue I'm bringing up would fix the `es.html`-as-english issue.

**Comment by aurels** [comment]
Hi Woody,

Thanks for reporting that ;-) It's a quite special case : Markdown inside HAML :-p

We are using this monstrous regex to extract GetText strings from HAML/SLIM : 
https://github.com/aurels/translation-gem/blob/master/lib/translation_io/extractor.rb

We support this syntax for GetText (without parentheses) : ` _ "Hello"` and that's what's clashing with Markdown's underscore. As you noticed.

We don't see a proper solution to that because it's a mix of two languages in the same file. Do you ?

**Comment by woahdae** [comment]
I'll have to think about it. My editor, for example, applies markdown styling (and CSS, JavaScript, etc) for those content blocks inside HAML. Maybe the "language inside a language" is not impossible, but just prohibitively expensive.

Worth noting that even plain HTML or ERB files can include inline styles and javascript, and ex. React and friends are moving towards packaging functionality rather than languages (lending itself to multiple languages in the same file).

**Comment by MichaelHoste** [comment]
Hi Woody,

The monstrous regexp we use is in fact a hack we need to use because of a limitation of Gettext. It should be able to parse everything correctly but in some case (RB files generated by HAML, per exemple), it is not able to find gettext expressions inside of interpolations (something like "#{_('hello')}"). And, bad news for us, it's exactly how RB files are generated from HAML.

We can continue to optimize our "hack" but there always will be some limitation. I guess the only solution is to update Gettext with another parser like it's suggested here: https://github.com/ruby-gettext/gettext/issues/42 and here: https://github.com/ruby-gettext/gettext/issues/4

But it's not something trivial like you could guess :p

**Comment by woahdae** [comment]
OK! Thanks for considering it.
